### obtener todas las movies
GET http://localhost:3000/movies

### obtener una movie por ID
GET http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### filtrar movies
GET http://localhost:3000/movies?genre=Drama

### crear una movie
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "La momia",
  "year": 2014,
  "director": "Christopher Nolan",
  "duration": 169,
  "poster": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.sensacine.com.mx%2Fpeliculas%2Fpelicula-20153%2F&psig=AOvVaw2ltT2ySgTNioL0vg3xfzp3&ust=1695467805346000&source=images&cd=vfe&opi=89978449&ved=0CBAQjRxqFwoTCJiM6_OLvoEDFQAAAAAdAAAAABAE",
  "genre": ["Adventure", "Drama", "Sci-Fi"],
  "rate": 8.6
}

### actualizar una movie
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
  "year": 2017,
  "director": "Rob Cohen"
}

### borrar una movie
DELETE http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
